/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Library_Management;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rashe
 */
public class AddMember extends javax.swing.JInternalFrame {

    Connection conn = null;
    PreparedStatement ps = null;
    ResultSet rs = null;

    public AddMember() {
        initComponents();
        conn = My_CNX.getConnection();
        autoId();
        tablelord();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        mid = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        nid = new javax.swing.JTextField();
        no = new javax.swing.JTextField();
        gender = new javax.swing.JComboBox<>();
        type = new javax.swing.JComboBox<>();
        bday = new com.toedter.calendar.JDateChooser();
        jPanel5 = new javax.swing.JPanel();
        add = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        mail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setPreferredSize(new java.awt.Dimension(1110, 730));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 39, 1280, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel10.setText("Add Member");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 100));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 110));

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Birthday");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 120, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Member Id");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 120, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 120, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Student ID");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 120, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Member Type");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 130, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("E-Mail");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 120, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Address");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 120, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Gender");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 120, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Contact No");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 120, 40));

        mid.setEditable(false);
        mid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(mid, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 240, 40));

        name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 240, 40));

        nid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(nid, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 240, 40));

        no.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(no, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, 240, 40));

        gender.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Gender", "Male", "Femail" }));
        gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderActionPerformed(evt);
            }
        });
        jPanel2.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 140, 40));
        gender.getAccessibleContext().setAccessibleName("");

        type.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Member Type", "Student", "Other" }));
        jPanel2.add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, 170, 40));
        jPanel2.add(bday, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 240, 40));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add.setBackground(new java.awt.Color(255, 102, 102));
        add.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel5.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 100, -1));

        update.setBackground(new java.awt.Color(255, 102, 102));
        update.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel5.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 100, -1));

        delete.setBackground(new java.awt.Color(255, 102, 102));
        delete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel5.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 100, -1));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 60, 210, 230));

        mail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, 240, 40));

        address.setColumns(20);
        address.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        address.setRows(5);
        jScrollPane1.setViewportView(address);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 240, 100));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 1090, 370));

        table.setBackground(new java.awt.Color(255, 255, 102));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 1100, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed

        String id = mid.getText();
        String uname = name.getText();
        String nic = nid.getText();
        String date = ((JTextField) bday.getDateEditor().getUiComponent()).getText();
        String gen = gender.getSelectedItem().toString();
        String add = address.getText();
        String email = mail.getText();
        String contac = no.getText();
        String typ = type.getSelectedItem().toString();

        try {

            String sql = "INSERT INTO `addmember`(`mid`, `name`, `student_id`, `birthday`, `gender`, `address`, `email`, `contact`, `type`) VALUES ('" + id + "','" + uname + "','" + nic + "','" + date + "','" + gen + "','" + add + "','" + email + "','" + contac + "','" + typ + "')";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.execute();
            JOptionPane.showMessageDialog(rootPane, "Successfully Insert");
            clearFild();

        } catch (Exception e) {

            JOptionPane.showMessageDialog(rootPane, e);

        }
        clearFild();
        autoId();
        tablelord();

    }//GEN-LAST:event_addActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked

        DefaultTableModel tmodel = (DefaultTableModel) table.getModel();
        int selectrowindex = table.getSelectedRow();

        mid.setText(tmodel.getValueAt(selectrowindex, 0).toString());
        name.setText(tmodel.getValueAt(selectrowindex, 1).toString());
        nid.setText(tmodel.getValueAt(selectrowindex, 2).toString());
        ((JTextField) bday.getDateEditor().getUiComponent()).setText(tmodel.getValueAt(selectrowindex, 3).toString());
        gender.setSelectedItem(tmodel.getValueAt(selectrowindex, 4).toString());
        address.setText(tmodel.getValueAt(selectrowindex, 5).toString());
        mail.setText(tmodel.getValueAt(selectrowindex, 6).toString());
        no.setText(tmodel.getValueAt(selectrowindex, 7).toString());
        type.setSelectedItem(tmodel.getValueAt(selectrowindex, 8).toString());

    }//GEN-LAST:event_tableMouseClicked

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        
        String id = mid.getText();
        String uname = name.getText();
        String nic = nid.getText();
        String date = ((JTextField) bday.getDateEditor().getUiComponent()).getText();
        String gen = gender.getSelectedItem().toString();
        String add = address.getText();
        String email = mail.getText();
        String contac = no.getText();
        String typ = type.getSelectedItem().toString();
        
        try {
            
            String sql = "UPDATE `addmember` SET `name`='"+uname+"',`student_id`='"+nic+"',`birthday`='"+date+"',`gender`='"+gen+"',`address`='"+add+"',`email`='"+email+"',`contact`='"+contac+"',`type`='"+typ+"' WHERE `mid`='"+id+"'";
            ps = conn.prepareStatement(sql);
            ps.execute();
            
            JOptionPane.showMessageDialog(rootPane, "Update Successfully");
            tablelord();
            clearFild();
            
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, e);
        }
        
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        
        try {
            
            String sql = "DELETE FROM `addmember` WHERE `mid`='"+mid.getText()+"'";
            ps = conn.prepareStatement(sql);
            ps.execute();
            JOptionPane.showMessageDialog(rootPane, "Delete Successfully");
            tablelord();
            clearFild();
            
        } catch (Exception e)
        {
            
            JOptionPane.showMessageDialog(rootPane, e);
            
        }
        
    }//GEN-LAST:event_deleteActionPerformed

    private void genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderActionPerformed

    private void tablelord() {

        try {

            String sql = "SELECT `mid`, `name`, `student_id`, `birthday`, `gender`, `address`, `email`, `contact`, `type` FROM `addmember` ";
            ps = conn.prepareStatement(sql);
            rs = ps.executeQuery();
            table.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {

            JOptionPane.showMessageDialog(rootPane, e);

        }

    }

    private void autoId() {
        try {

            String sql = "SELECT `mid`  FROM `addmember`    ORDEr By mid DESC LIMIT 1";

            ps = (PreparedStatement) conn.prepareStatement(sql);
            rs = ps.executeQuery();
            if (rs.next()) {
                String rnno = rs.getString("mid");
                int co = rnno.length();
                String txt = rnno.substring(0, 2);
                String num = rnno.substring(2, co);
                int n = Integer.parseInt(num);
                n++;
                String snum = Integer.toString(n);
                String ftxt = txt + snum;
                mid.setText(ftxt);
            } else {
                mid.setText("MI1000");
            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(rootPane, e);

        }

    }

    private void clearFild() {

      //  mid.setText("");
        name.setText("");
        nid.setText("");
        ((JTextField) bday.getDateEditor().getUiComponent()).setText("");
        gender.setSelectedIndex(0);
        address.setText("");
        mail.setText("");
        no.setText("");
        type.setSelectedIndex(0);

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTextArea address;
    private com.toedter.calendar.JDateChooser bday;
    private javax.swing.JButton delete;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField mail;
    private javax.swing.JTextField mid;
    private javax.swing.JTextField name;
    private javax.swing.JTextField nid;
    private javax.swing.JTextField no;
    private javax.swing.JTable table;
    private javax.swing.JComboBox<String> type;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
